# Generated by Django 4.2 on 2024-02-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.CharField(default='client', max_length=50),
            preserve_default=False,
        ),
    ]
