# Generated by Django 4.2 on 2024-02-24 17:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('email', 'name', 'users')},
        ),
    ]
