# Generated by Django 4.2 on 2024-02-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('email', 'name')},
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
