# Generated by Django 4.2 on 2024-02-15 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0005_rename_first_name_client_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('email', 'name', 'users')},
        ),
    ]
