# Generated by Django 4.2 on 2024-03-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=11)),
                ('body', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/blog')),
                ('views', models.IntegerField(default=0)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BlogUnit',
                'verbose_name_plural': 'BlogUnits',
            },
        ),
    ]
