# Generated by Django 4.2 on 2024-02-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('output_messages', '0003_outputmessage_body'),
        ('clients', '0003_alter_client_unique_together'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='output_messages.outputmessage'),
        ),
    ]
