# Generated by Django 4.2 on 2024-02-25 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_remove_mailing_clients_remove_mailing_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
    ]
