# Generated by Django 4.2 on 2024-02-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_unique_together'),
        ('mailings', '0003_remove_mailing_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='clients.client'),
        ),
    ]
