# Generated by Django 4.2 on 2024-02-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_mailing_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_status',
            field=models.SmallIntegerField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='mailing',
            name='mailing_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
