# Generated by Django 4.2 on 2024-02-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_alter_mailing_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.IntegerField(default=1),
        ),
    ]
