# Generated by Django 4.2 on 2024-02-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0009_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
