# Generated by Django 4.2 on 2024-02-25 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0012_alter_mailing_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_time',
            field=models.TimeField(default=datetime.time(2, 18, 18, 600975)),
        ),
    ]
