# Generated by Django 4.2 on 2024-02-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0015_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.IntegerField(default=0),
        ),
    ]
