# Generated by Django 4.2 on 2024-02-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0016_alter_mailing_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('manager', 'Can view all mailing')], 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
