# Generated by Django 4.2 on 2024-02-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='users',
            new_name='user',
        ),
    ]
