# Generated by Django 4.2 on 2024-02-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output_messages', '0002_alter_outputmessage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputmessage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
